window.ColorPaletteLocales=window.ColorPaletteLocales||{};
window.ColorPaletteLocales['en-US']={
  code:'en-US',
  name:'English',
  ui:{
    '发现':'Discover','取色':'Extract','创作':'Create','颜色百科':'Color Library','收藏':'Favorites','工作区':'Workspace',
    '从图片取色':'Extract from Image','开始创作':'Start Creating','浏览颜色百科':'Browse Color Library','精选色卡':'Featured Palettes',
    '三步完成一张色卡':'Create a Palette in Three Steps','找色':'Find Colors','生成':'Generate','保存':'Save','搜索名称、英文名或 HEX':'Search name, English name, or HEX',
    '点击色块查看详情':'Click a color to view details','色彩体系':'Color System','色相分类':'Color Family','全部':'All',
    '类似色':'Analogous','互补色':'Complementary','分裂互补':'Split Complementary','三角色':'Triadic','四角色':'Tetradic','双互补':'Double Complementary',
    '单色阶':'Monochromatic','浅色阶':'Tints','深色阶':'Shades','柔和色阶':'Tones','粉彩':'Pastel','鲜艳':'Vivid','暖色':'Warm','冷色':'Cool','灰阶':'Grayscale',
    '颜色':'Colors','配色模式':'Palette Modes','命名颜色':'Named Colors','浏览器本地优先':'Local-first in your browser','图片不会上传到服务器':'Images are never uploaded to a server',
    '我的色卡':'My Palette','我的收藏':'My Favorites','最近使用':'Recently Used','新建色卡':'New Palette','保存色卡':'Save Palette','导出':'Export','删除':'Delete','复制':'Copy','应用':'Use','使用':'Use','清空':'Clear',
    '取消':'Cancel','确认':'Confirm','名称':'Name','来源':'Source','自定义':'Custom','添加颜色':'Add Color','移除':'Remove','上传图片':'Upload Image','选择图片':'Choose Image',
    '从图片中提取颜色':'Extract colors from an image','打开创作':'Open Studio','重新取色':'Pick Again','暂无收藏':'No favorites yet','暂无色卡':'No saved palettes yet','暂无最近颜色':'No recent colors yet',
    '颜色关系':'Color Relationships','相近颜色':'Nearby Colors','色阶':'Lightness Scale','对比度':'Contrast','颜色信息':'Color Information','复制 HEX':'Copy HEX','收藏颜色':'Favorite Color','取消收藏':'Unfavorite',
    '明度':'Lightness','饱和度':'Saturation','色相':'Hue','对比度等级':'Contrast Grade','可读性':'Readability','导出 JSON':'Export JSON','导出 CSS':'Export CSS',
    '重置':'Reset','随机':'Random','刷新':'Refresh','添加到色卡':'Add to Palette','进入颜色百科':'Open Color Library','返回':'Back','下一步':'Next','上一步':'Previous',
    '中 / 日传统色 · CSS · 颜料':'Traditional Chinese / Japanese colors · CSS · pigments','按色彩体系、色相和名称快速定位颜色；点色块查看完整参数、相近颜色与色阶。':'Find colors by system, hue, or name; open a swatch for full parameters, nearby colors, and scales.',
    '来自整理后的多套色彩体系':'Curated from multiple color systems','类似、互补、三角色、粉彩、冷暖等':'Analogous, complementary, triadic, pastel, warm/cool, and more','选择类似、互补、三角色、粉彩、冷暖等配色方式。':'Choose analogous, complementary, triadic, pastel, warm/cool, and other schemes.',
    '搜索名称、HEX，或者按色彩体系与色相浏览。':'Search by name or HEX, or browse by color system and hue.','把最终颜色组合保存到自己的色卡库。':'Save the final combination to your personal palette library.','原生浏览器运行，图片和收藏数据留在本机。':'Runs natively in the browser; images and saved data stay on this device.',
    '日间模式':'Light mode','夜间模式':'Dark mode','颜色工作台':'Color workspace','颜色工具箱':'Color toolkit','配色':'Palette','取色结果':'Extraction Results','上传或拖入图片':'Upload or drop an image','点击图片取色':'Click the image to pick a color','没有可用颜色':'No colors available','暂无内容':'Nothing here yet','专业版':'Pro','升级':'Upgrade','已复制':'Copied','复制失败':'Copy failed',
    '自定义颜色':'Custom Color','未知':'Unknown','已收藏':'Favorited','用于创作':'Use in Studio','颜色参数':'Color Parameters','每组关系都可以完整带入 Palette Studio。':'Each relationship can be brought into Palette Studio.','感知明度阶':'Perceptual Lightness Scale','使用 OKLab Lightness 构建比传统 HSL 更连贯的明度渐变，适合 UI 层级、背景和状态。':'OKLab Lightness produces a more coherent lightness ramp than traditional HSL for UI hierarchy, backgrounds, and states.','对比度检查':'Contrast Check','白色背景':'White background','黑色背景':'Black background','对比度遵循 WCAG 相对亮度公式。':'Contrast follows the WCAG relative luminance formula.','附近颜色':'Nearby Colors','OKLab 距离':'OKLab Distance',
    '色卡名称':'Palette name','配色关系':'Color relationship','加入当前颜色':'Add current color','当前色卡':'Current palette','生成：':'Generate:','删除':'Delete','至少需要 2 个颜色':'At least 2 colors are required','色卡已保存':'Palette saved','图片色卡':'Image Palette','图片色卡已保存':'Image palette saved','选择一张图片开始。':'Choose an image to begin.','选择一张图片开始。支持 JPG、PNG、WebP 等浏览器可读取格式。':'Choose an image to begin. JPG, PNG, WebP, and other browser-readable formats are supported.','尚未提取颜色。':'No colors extracted yet.','主色':'Primary','强调色':'Accent','辅助色':'Support','收藏内容':'Favorite Content','确定清空全部收藏？':'Clear all favorites?','还没有收藏。去颜色百科或 Palette Studio 保存一些颜色。':'No favorites yet. Save colors from the Color Library or Palette Studio.','编辑':'Edit','移除':'Remove','复制色值':'Copy Color Values','工作区还是空的。':'Your workspace is empty.','最近颜色':'Recent Colors','暂无最近颜色。':'No recent colors.','Pro 能力预留':'Pro Preview','当前 GitHub Pages 版本优先保持免费、本地优先和无账号使用。这里保留未来扩展入口，不伪造支付或会员系统。':'The current GitHub Pages version stays free, local-first, and account-free. This area reserves room for future expansion without pretending there is a payment or membership system.','更高级的色彩空间':'Advanced Color Spaces','继续扩展 OKLab / OKLCH、DeltaE、可访问性检查和感知均匀的配色算法。':'Further expand OKLab / OKLCH, DeltaE, accessibility checks, and perceptually uniform palette algorithms.','更完整的导出':'Richer Export','可扩展 CSS、SCSS、JSON、Design Tokens、Tailwind 等开发工作流导出。':'Extend exports for CSS, SCSS, JSON, Design Tokens, Tailwind, and other development workflows.','工作区同步':'Workspace Sync','未来可以增加可选云同步；当前版本不上传你的图片或本地色卡。':'Optional cloud sync could be added later; the current version does not upload your images or local palettes.',
    '提取结果':'Extraction Results','保存为色卡':'Save as Palette','打开 Palette Studio':'Open Palette Studio','清除':'Clear','颜色已收藏':'Color added to favorites','已取消收藏':'Removed from favorites','重新加载':'Reload','颜色数据加载失败：':'Failed to load color data:','确定删除？':'Delete this item?','颜色已复制':'Color copied','工作区':'Workspace','我的色卡':'My Palettes','最近使用的颜色':'Recently Used Colors'
  },
  keys:{
    nav:{discover:'Discover',extractor:'Extract',create:'Create',library:'Color Library',favorites:'Favorites',workspace:'Workspace'},
    common:{save:'Save',copy:'Copy',delete:'Delete',cancel:'Cancel',confirm:'Confirm',export:'Export',reset:'Reset',random:'Random',refresh:'Refresh',back:'Back',next:'Next',previous:'Previous',apply:'Use',use:'Use',clear:'Clear',remove:'Remove'},
    home:{eyebrow:'Color Toolkit',title:'Find colors, then make your own.',extract:'Extract from Image',create:'Start Creating',library:'Color Library',featured:'Featured Palettes',steps:'Create a Palette in Three Steps'},
    library:{title:'Color Library',searchPlaceholder:'Search name, English name, or HEX',system:'Color System',family:'Color Family',all:'All',count:'{count} colors',detail:'Click a color to view details'},
    color:{relationships:'Color Relationships',nearby:'Nearby Colors',scale:'Lightness Scale',contrast:'Contrast',information:'Color Information',copyHex:'Copy HEX',favorite:'Favorite Color',unfavorite:'Unfavorite'},
    palette:{name:'My Palette',new:'New Palette',save:'Save Palette',addColor:'Add Color',empty:'No saved palettes yet'},
    extractor:{title:'Extract',upload:'Upload or drop an image',pick:'Click the image to pick a color',result:'Extraction Results',repick:'Pick Again'},
    workspace:{title:'Workspace',recent:'Recently Used',emptyRecent:'No recent colors yet'},
    favorites:{title:'My Favorites',empty:'No favorites yet'},
    pro:{title:'Pro',upgrade:'Upgrade'}
  },
  relations:{analogous:'Analogous',complementary:'Complementary',split:'Split Complementary',triadic:'Triadic',tetradic:'Tetradic',doubleComplementary:'Double Complementary',warm:'Warm Range',cool:'Cool Range',monochromatic:'Monochromatic',tints:'Tints',shades:'Shades',tones:'Tones'},
  relationDescriptions:{analogous:'Adjacent hues create a unified, calm palette.',complementary:'Opposite hues create strong separation and contrast.',split:'The base color is paired with the two hues beside its complement.',triadic:'Three evenly spaced hues create balanced color contrast.',tetradic:'Two complementary pairs form a four-color relationship.',doubleComplementary:'Two neighboring colors are combined with their opposites.',warm:'Shifts around the base color toward warmer hues.',cool:'Shifts around the base color toward cooler hues.',monochromatic:'Keeps the hue while changing lightness.',tints:'Reduces saturation and increases lightness for lighter variants.',shades:'Reduces lightness to create darker variants.',tones:'Reduces saturation for restrained interface palettes.'},
  modes:{analogous:'Analogous',complementary:'Complementary',split:'Split Complementary',triadic:'Triadic',tetradic:'Tetradic',doubleComplementary:'Double Complementary',monochromatic:'Monochromatic',tints:'Tints',shades:'Shades',tones:'Tones',pastel:'Pastel',vivid:'Vivid',warm:'Warm',cool:'Cool',grayscale:'Grayscale'}
};
