window.ColorPaletteLocales=window.ColorPaletteLocales||{};
window.ColorPaletteLocales['zh-CN']={code:'zh-CN',name:'简体中文',ui:{
'nav.discover':'发现','nav.extractor':'取色','nav.create':'创作','nav.library':'颜色百科','nav.favorites':'收藏','nav.workspace':'工作区',
'shell.homeLabel':'ColorPalette 首页','shell.mainNav':'主导航','shell.mobileNav':'移动端导航','shell.preferences':'界面偏好设置','shell.language':'切换中文 / English','shell.theme':'切换日间 / 夜间模式','shell.lightMode':'日间模式','shell.darkMode':'夜间模式','shell.lightSwitch':'切换到日间模式','shell.darkSwitch':'切换到夜间模式','shell.localFirst':'浏览器本地优先','shell.noUpload':'图片不会上传到服务器','shell.documentTitle':'ColorPalette — 颜色工作台','shell.documentDescription':'ColorPalette：图片取色、颜色百科、配色生成、色卡收藏与工作区。',
'home.eyebrow':'颜色工具箱','home.title':'找到颜色，也做出自己的颜色。','home.intro':'从图片取色、颜色百科、配色生成开始，再把结果整理成自己的色卡。所有操作都在浏览器内完成。','home.extract':'从图片取色','home.create':'开始创作','home.library':'颜色百科','home.libraryMeta':'个命名颜色 · 中 / 日传统色 · CSS · 颜料','home.discover':'发现','home.featured':'精选色卡','home.browseLibrary':'浏览颜色百科','home.stepsTitle':'三步完成一张色卡','home.stepFind':'找色','home.stepFindNote':'搜索名称、HEX，或者按色彩体系与色相浏览。','home.stepGenerate':'生成','home.stepGenerateNote':'选择类似、互补、三角色、粉彩、冷暖等配色方式。','home.stepSave':'保存','home.stepSaveNote':'把最终颜色组合保存到自己的色卡库。',
'stats.namedColors':'命名颜色','stats.namedColorsNote':'来自整理后的多套色彩体系','stats.paletteModes':'配色模式','stats.paletteModesNote':'类似、互补、三角色、粉彩、冷暖等',
'library.eyebrow':'颜色百科','library.title':'颜色百科','library.subtitle':'按色彩体系、色相和名称快速定位颜色；点色块查看完整参数、相近颜色与色阶。','library.system':'色彩体系','library.family':'色相分类','library.searchPlaceholder':'搜索名称、英文名或 HEX','library.count':'{count} 个颜色','library.detail':'点击色块查看详情','library.empty':'没有找到匹配颜色。',
'detail.eyebrow':'颜色详情','detail.useInStudio':'用于创作','detail.favorited':'已收藏','detail.favorite':'收藏颜色','detail.copyHex':'复制 HEX','detail.parameters':'颜色参数','detail.relationships':'颜色关系','detail.relationshipNote':'每组关系都可以完整带入 Palette Studio。','detail.lightnessScale':'感知明度阶','detail.lightnessNote':'使用 OKLab Lightness 构建比传统 HSL 更连贯的明度渐变，适合 UI 层级、背景和状态。','detail.contrast':'对比度检查','detail.whiteBackground':'白色背景','detail.blackBackground':'黑色背景','detail.contrastNote':'对比度遵循 WCAG 相对亮度公式。','detail.nearby':'附近颜色','detail.distance':'距离',
'color.custom':'自定义颜色','color.customCollection':'自定义','color.unknown':'未知','color.userInput':'用户输入','color.collection':'颜色体系',
'create.eyebrow':'创作','create.title':'Palette Studio','create.subtitle':'从一个颜色开始，生成关系色，手动编辑并保存为自己的色卡。','create.name':'色卡名称','create.hue':'色相','create.saturation':'饱和度','create.lightness':'明度','create.relationship':'配色关系','create.addCurrent':'加入当前颜色','create.currentPalette':'当前色卡','create.empty':'当前色卡还没有颜色。','create.generated':'生成：','create.minColors':'至少需要 2 个颜色',
'extractor.eyebrow':'图片取色','extractor.title':'从图片取色','extractor.subtitle':'图片只在浏览器内处理。自动提取代表色，也可以直接点击图片获取像素 HEX。','extractor.choose':'选择图片','extractor.choosePlaceholder':'选择一张图片开始。','extractor.placeholder':'选择一张图片开始。支持 JPG、PNG、WebP 等浏览器可读取格式。','extractor.results':'取色结果','extractor.noResults':'尚未提取颜色。','extractor.savePalette':'保存为色卡','extractor.openStudio':'打开创作','extractor.imagePalette':'图片色卡','extractor.primary':'主色','extractor.accent':'强调色','extractor.support':'辅助色','extractor.samples':'采样',
'favorites.eyebrow':'收藏','favorites.title':'我的收藏','favorites.subtitle':'保存的颜色与色卡都留在浏览器本地。','favorites.content':'收藏内容','favorites.empty':'还没有收藏。去颜色百科或 Palette Studio 保存一些颜色。','favorites.clearConfirm':'确定清空全部收藏？',
'workspace.eyebrow':'工作区','workspace.title':'工作区','workspace.subtitle':'集中查看本机保存的色卡、最近使用的颜色，并继续编辑。','workspace.colors':'个颜色','workspace.copyValues':'复制色值','workspace.empty':'工作区还是空的。','workspace.recent':'最近颜色','workspace.emptyRecent':'暂无最近颜色。',
'palette.title':'我的色卡','palette.defaultName':'我的色卡','palette.new':'新建色卡','palette.save':'保存色卡',
'pro.title':'专业版','pro.subtitle':'当前 GitHub Pages 版本优先保持免费、本地优先和无账号使用。这里保留未来扩展入口，不伪造支付或会员系统。','pro.advancedSpaces':'更高级的色彩空间','pro.advancedSpacesNote':'继续扩展 OKLab / OKLCH、DeltaE、可访问性检查和感知均匀的配色算法。','pro.richerExport':'更完整的导出','pro.richerExportNote':'可扩展 CSS、SCSS、JSON、Design Tokens、Tailwind 等开发工作流导出。','pro.workspaceSync':'工作区同步','pro.workspaceSyncNote':'未来可以增加可选云同步；当前版本不上传你的图片或本地色卡。',
'common.copy':'复制','common.delete':'删除','common.remove':'移除','common.clear':'清空','common.edit':'编辑','common.use':'使用','common.exportCss':'导出 CSS','common.exportJson':'导出 JSON','common.moveUp':'上移','common.moveDown':'下移',
'status.copied':'已复制','status.copyFailed':'复制失败','status.colorFavorited':'颜色已收藏','status.favoriteRemoved':'已取消收藏','status.paletteSaved':'色卡已保存','status.imagePaletteSaved':'图片色卡已保存','errors.dataLoad':'颜色数据加载失败：','errors.reload':'重新加载'
},relations:{analogous:'类似色',complementary:'互补色',split:'分裂互补',triadic:'三角色',tetradic:'四角色',doubleComplementary:'双互补',warm:'暖色范围',cool:'冷色范围',monochromatic:'单色阶',tints:'浅色阶',shades:'深色阶',tones:'柔和色阶'},relationDescriptions:{analogous:'相邻色相，适合形成统一、平静的配色。',complementary:'色相环对置，适合形成强烈分离。',split:'基础色搭配互补色两侧的两个强调色。',triadic:'三等分色相，保持均衡的色彩对比。',tetradic:'两组互补色构成的四角色关系。',doubleComplementary:'两个邻近色分别与其对立色组合。',warm:'围绕基础色向暖色方向偏移。',cool:'围绕基础色向冷色方向偏移。',monochromatic:'保持色相，只改变明度。',tints:'降低饱和度并提高明度。',shades:'降低明度形成深色版本。',tones:'降低饱和度，适合克制型界面。'},modes:{analogous:'类似色',complementary:'互补色',split:'分裂互补',triadic:'三角色',tetradic:'四角色',doubleComplementary:'双互补',monochromatic:'单色阶',tints:'浅色阶',shades:'深色阶',tones:'柔和色阶',pastel:'粉彩',vivid:'鲜艳',warm:'暖色',cool:'冷色',grayscale:'灰阶'},meta:{families:{'红':'红','橙':'橙','黄':'黄','绿':'绿','青':'青','蓝':'蓝','紫':'紫','粉':'粉','棕':'棕','中性':'中性'},categories:{'all':'全部','基础色':'基础色','CSS 标准色':'CSS 标准色','基础颜色':'基础颜色','CSS 命名颜色':'CSS 命名颜色','中国传统色':'中国传统色','日本传统色':'日本传统色','艺术与颜料':'艺术与颜料'},categoryAllKey:'all',familyAllKey:'all'}};
